### ISSUE TITLE
Error when using latest vitest version

### ISSUE THREAD

**Issue by fnebenfuehr** [cenfun/merge-code-coverage-vitest#1]
```
TypeError: _a.generateCoverage is not a function
 ❯ node_modules/vitest/dist/vendor/cli-api.CTkP2Ier.js:14954:82
 ❯ Vitest.runFiles node_modules/vitest/dist/vendor/cli-api.CTkP2Ier.js:14962:12
 ❯ Vitest.start node_modules/vitest/dist/vendor/cli-api.CTkP2Ier.js:14808:7
 ❯ startVitest node_modules/vitest/dist/vendor/cli-api.CTkP2Ier.js:15915:7
 ❯ start node_modules/vitest/dist/vendor/cac.DFtWvZc2.js:1502:17
 ❯ CAC.run node_modules/vitest/dist/vendor/cac.DFtWvZc2.js:1482:3
```

Steps to reproduce:
1. `git clone git@github.com:cenfun/merge-code-coverage-vitest.git`
2. Update vitest to version 2.x
3. Generate report

**Comment by cenfun** [comment]
It should be fixed. there is update to [vitest-monocart-coverage](https://github.com/cenfun/vitest-monocart-coverage) for support vitest v2.
please update the dependencies and try again.

**Comment by fnebenfuehr** [comment]
Works like charm. Thank you for the super fast response.
